/*
 * SPDX-FileCopyrightText: 2026 Kebag-Logic
 * SPDX-License-Identifier: MIT
 *
 * pcap reader tests plus in-process golden-trace runs (TV-1/TV-2) over the
 * scenarios generated by tools/gen_pcaps.py. Run from the repo root.
 */
#include <cstdio>
#include <fstream>

#include "engine/engine.h"
#include "pcapio/pcap_reader.h"
#include "test.h"

using namespace avb;

namespace {

std::string tmpFile(const std::string& name) {
    return "build/" + name;
}

void writeFile(const std::string& path, const std::string& bytes) {
    std::ofstream f(path, std::ios::binary | std::ios::trunc);
    f.write(bytes.data(), (std::streamsize)bytes.size());
}

void put32le(std::string& s, uint32_t v) {
    s.push_back((char)(v & 0xff));
    s.push_back((char)((v >> 8) & 0xff));
    s.push_back((char)((v >> 16) & 0xff));
    s.push_back((char)((v >> 24) & 0xff));
}
void put16le(std::string& s, uint16_t v) {
    s.push_back((char)(v & 0xff));
    s.push_back((char)((v >> 8) & 0xff));
}

std::shared_ptr<Session> runSession(const std::string& pcapPath) {
    Engine engine;
    auto s = std::make_shared<Session>();
    s->id = "t1";
    s->name = pcapPath;
    s->pcapFilePath = pcapPath;
    engine.start(s);
    engine.drain();
    return s;
}

size_t countTransitions(const Session& s, const std::string& needle) {
    size_t n = 0;
    for (auto& e : s.events)
        if (e.kind == Kind::Transition && e.summary.find(needle) != std::string::npos)
            ++n;
    return n;
}

} // namespace

TEST(pcap_classic_microseconds) {
    std::string f;
    put32le(f, 0xa1b2c3d4);
    put16le(f, 2);
    put16le(f, 4);
    put32le(f, 0);
    put32le(f, 0);
    put32le(f, 262144);
    put32le(f, 1); // Ethernet
    // one 60-byte packet at t=1.5
    put32le(f, 1700000001);
    put32le(f, 500000);
    put32le(f, 60);
    put32le(f, 60);
    f.append(60, '\0');
    writeFile(tmpFile("t_classic.pcap"), f);

    PcapFile p;
    std::string err;
    CHECK(p.open(tmpFile("t_classic.pcap"), err));
    CHECK_EQ(p.packets().size(), (size_t)1);
    CHECK_EQ(p.packets()[0].tsNanos, 1700000001500000000ull);
    CHECK_EQ(p.packets()[0].caplen, 60u);
}

TEST(pcap_rejects_bad_input) {
    PcapFile p;
    std::string err;
    writeFile(tmpFile("t_bad.pcap"), "this is not a capture at all");
    CHECK(!p.open(tmpFile("t_bad.pcap"), err));
    CHECK(!err.empty());

    // Non-Ethernet link type is refused (v1) and named in the error.
    std::string f;
    put32le(f, 0xa1b2c3d4);
    put16le(f, 2);
    put16le(f, 4);
    put32le(f, 0);
    put32le(f, 0);
    put32le(f, 262144);
    put32le(f, 113); // LINKTYPE_LINUX_SLL, "any" interface
    writeFile(tmpFile("t_sll.pcap"), f);
    PcapFile p2;
    CHECK(!p2.open(tmpFile("t_sll.pcap"), err));
    CHECK(err.find("Linux cooked/SLL") != std::string::npos);
    CHECK(err.find("\"any\"") != std::string::npos);
}

TEST(pcapng_mpacket_preamble_stripped) {
    std::string f;
    // SHB
    put32le(f, 0x0a0d0d0a);
    put32le(f, 28);
    put32le(f, 0x1a2b3c4d);
    put16le(f, 1);
    put16le(f, 0);
    put32le(f, 0xffffffff);
    put32le(f, 0xffffffff);
    put32le(f, 28);
    // IDB: 802.3br mPacket (ProfiShark preamble mode)
    put32le(f, 1);
    put32le(f, 20);
    put16le(f, 274);
    put16le(f, 0);
    put32le(f, 0);
    put32le(f, 20);
    // EPB: preamble(7×0x55) + SFD(0xD5) + 60-byte frame + 4-byte FCS
    const uint32_t caplen = 8 + 60 + 4;
    put32le(f, 6);
    put32le(f, 32 + caplen);
    put32le(f, 0);
    put32le(f, 0);
    put32le(f, 1000);
    put32le(f, caplen);
    put32le(f, caplen);
    f.append(7, '\x55');
    f.push_back('\xd5');
    f.push_back('\x01'); // frame starts with the MSRP multicast dst
    f.append(59, '\0');
    f.append(4, '\xAA'); // FCS
    put32le(f, 32 + caplen);
    writeFile(tmpFile("t_mpacket.pcapng"), f);

    PcapFile p;
    std::string err;
    CHECK(p.open(tmpFile("t_mpacket.pcapng"), err));
    CHECK_EQ(err, std::string());
    CHECK_EQ(p.packets().size(), (size_t)1);
    CHECK_EQ(p.packets()[0].caplen, 64u);       // preamble+SFD gone
    CHECK_EQ(p.packetData(0)[0], (uint8_t)0x01); // frame starts at dst MAC
}

TEST(pcapng_names_non_ethernet_linktype) {
    std::string f;
    // SHB
    put32le(f, 0x0a0d0d0a);
    put32le(f, 28);
    put32le(f, 0x1a2b3c4d);
    put16le(f, 1);
    put16le(f, 0);
    put32le(f, 0xffffffff);
    put32le(f, 0xffffffff);
    put32le(f, 28);
    // IDB: Linux SLL2 (captured on "any")
    put32le(f, 1);
    put32le(f, 20);
    put16le(f, 276);
    put16le(f, 0);
    put32le(f, 0);
    put32le(f, 20);
    writeFile(tmpFile("t_sll2.pcapng"), f);

    PcapFile p;
    std::string err;
    CHECK(!p.open(tmpFile("t_sll2.pcapng"), err));
    CHECK(err.find("no Ethernet interface") != std::string::npos);
    CHECK(err.find("SLL2") != std::string::npos);
}

TEST(pcapng_basic) {
    std::string f;
    // SHB
    put32le(f, 0x0a0d0d0a);
    put32le(f, 28);
    put32le(f, 0x1a2b3c4d);
    put16le(f, 1);
    put16le(f, 0);
    put32le(f, 0xffffffff);
    put32le(f, 0xffffffff);
    put32le(f, 28);
    // IDB: Ethernet, default µs resolution
    put32le(f, 1);
    put32le(f, 20);
    put16le(f, 1);
    put16le(f, 0);
    put32le(f, 0);
    put32le(f, 20);
    // EPB with one 64-byte packet
    uint64_t tsUs = 1700000002000123ull;
    put32le(f, 6);
    put32le(f, 32 + 64);
    put32le(f, 0);
    put32le(f, (uint32_t)(tsUs >> 32));
    put32le(f, (uint32_t)tsUs);
    put32le(f, 64);
    put32le(f, 64);
    f.append(64, '\0');
    put32le(f, 32 + 64);
    writeFile(tmpFile("t_ng.pcapng"), f);

    PcapFile p;
    std::string err;
    CHECK(p.open(tmpFile("t_ng.pcapng"), err));
    CHECK_EQ(err, std::string());
    CHECK_EQ(p.packets().size(), (size_t)1);
    CHECK_EQ(p.packets()[0].tsNanos, tsUs * 1000);
}

// ---- golden traces (TV-1) -------------------------------------------------

TEST(golden_msrp_basic) {
    auto s = runSession("testdata/msrp_basic.pcap");
    CHECK_EQ(s->status.load(), (int)Session::Done);
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK_EQ(s->packets.load(), (uint64_t)7);
    CHECK(countTransitions(*s, "-> PENDING") >= 1);
    CHECK(countTransitions(*s, "-> ESTABLISHED") == 1);
    CHECK(countTransitions(*s, "-> WITHDRAWN") == 1);
    std::string st = s->stateJson();
    CHECK(st.find("\"state\":\"WITHDRAWN\"") != std::string::npos);
    CHECK(st.find("\"vid\":2") != std::string::npos);
    CHECK(st.find("\"class_id\":6") != std::string::npos);
}

TEST(golden_msrp_failure) {
    auto s = runSession("testdata/msrp_failure.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "-> TALKER_FAILED") == 1);
    CHECK(s->stateJson().find("INSUFFICIENT_BANDWIDTH") == std::string::npos
              ? s->stateJson().find("\"failure_code\":1") != std::string::npos
              : true);
}

TEST(golden_mvrp) {
    auto s = runSession("testdata/mvrp.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "-> REGISTERED") >= 2); // join + rejoin
    CHECK(countTransitions(*s, "-> LEAVING") == 1);    // LeaveAll
    CHECK(countTransitions(*s, "-> WITHDRAWN") == 1);
}

TEST(golden_maap) {
    auto s = runSession("testdata/maap.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "-> PROBING") >= 2);
    CHECK(countTransitions(*s, "-> ACQUIRED") >= 2);
    CHECK(countTransitions(*s, "-> DEFENDING") == 1);
    CHECK(countTransitions(*s, "-> LOST") == 1);
}

TEST(golden_adp) {
    auto s = runSession("testdata/adp.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "-> AVAILABLE") >= 2);
    CHECK(countTransitions(*s, "-> DEPARTING") == 1);
    CHECK(countTransitions(*s, "restarted") == 1);
    CHECK(countTransitions(*s, "-> TIMED_OUT") == 1);
}

TEST(golden_aecp) {
    auto s = runSession("testdata/aecp.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    std::string st = s->stateJson();
    // Name learned, then renamed via SET_NAME.
    CHECK(countTransitions(*s, "Stage Box FOH") >= 1);
    CHECK(st.find("Stage Box Monitor") != std::string::npos);
    CHECK(countTransitions(*s, "timed out") == 1);
    CHECK(st.find("\"unsolicited\":1") != std::string::npos);
}

TEST(golden_acmp) {
    auto s = runSession("testdata/acmp.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "-> CONNECTED") == 1);
    CHECK(countTransitions(*s, "-> DISCONNECTED") == 1);
    CHECK(countTransitions(*s, "-> FAILED") == 2); // status + timeout
    std::string st = s->stateJson();
    CHECK(st.find("\"dest_mac\":\"91:e0:f0:00:0e:80\"") != std::string::npos);
}

TEST(golden_gptp_steady) {
    auto s = runSession("testdata/gptp_steady.pcap");
    CHECK_EQ(s->status.load(), (int)Session::Done);
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "NO_GM -> GM_PRESENT") == 1);
    CHECK(countTransitions(*s, "-> SYNC_HEALTHY") == 1);
    CHECK(countTransitions(*s, "-> MASTER") == 1);
    CHECK(countTransitions(*s, "-> SLAVE") == 1);
    CHECK(countTransitions(*s, "-> AS_CAPABLE") == 2); // both directions
    std::string st = s->stateJson();
    CHECK(st.find("\"state\":\"GM_PRESENT\"") != std::string::npos);
    CHECK(st.find("\"sync\":\"HEALTHY\"") != std::string::npos);
    CHECK(st.find("\"sync_interval_ms\":125") != std::string::npos);
    CHECK(st.find("\"last_turnaround_us\":800") != std::string::npos);
}

TEST(golden_gptp_gm_change) {
    auto s = runSession("testdata/gptp_gm_change.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "BMCA reselection") == 1);
    CHECK(countTransitions(*s, "took over as Sync sender") == 1);
    std::string st = s->stateJson();
    CHECK(st.find("\"clock_identity\":\"" + idStr(0x001b92fffe000002ull) + "\"") !=
          std::string::npos); // final GM is B
}

TEST(golden_gptp_sync_loss) {
    auto s = runSession("testdata/gptp_sync_loss.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "-> SYNC_LOST") == 1);
    CHECK(countTransitions(*s, "Sync resumed") == 1);
    // Announces kept flowing: the GM never timed out.
    CHECK(countTransitions(*s, "-> GM_TIMED_OUT") == 0);
}

TEST(golden_gptp_pdelay) {
    auto s = runSession("testdata/gptp_pdelay.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "-> AS_CAPABLE") == 1);
    CHECK(countTransitions(*s, "exceeds the 10 ms limit") == 1);
    CHECK(countTransitions(*s, "-> NOT_AS_CAPABLE") == 1);
}

TEST(golden_gptp_adp_stale_gm) {
    auto s = runSession("testdata/gptp_adp_stale_gm.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "stale gPTP info") == 1);
    CHECK(countTransitions(*s, "now matches the observed grandmaster") == 1);
    // SYNC_LOST names the established reservation depending on the clock.
    bool cited = false;
    for (auto& e : s->events)
        if (e.kind == Kind::Transition &&
            e.summary.find("SYNC_LOST") != std::string::npos &&
            e.summary.find("1 established stream reservation") != std::string::npos)
            cited = true;
    CHECK(cited);
    std::string st = s->stateJson();
    CHECK(st.find("\"gm_in_sync\":\"MATCH\"") != std::string::npos);
    CHECK(st.find("\"gptp_sync\":\"HEALTHY\"") != std::string::npos);
}

TEST(golden_gptp_bmca) {
    auto s = runSession("testdata/gptp_bmca.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    // BMCA is a /state readout, not an event source — handovers are narrated
    // by GM_CHANGED, and no BMCA text events are emitted.
    CHECK(countTransitions(*s, "election not converged") == 0);
    CHECK(countTransitions(*s, "AGED") >= 1); // A's announces stop in phase 3
    std::string st = s->stateJson();
    // Ends converged on B (prio1 200) once it drives Sync.
    CHECK(st.find("\"bmca\":\"CONVERGED\"") != std::string::npos);
    CHECK(st.find("\"expected_gm\":\"" + idStr(0x001b92fffe000002ull) + "\"") !=
          std::string::npos);
}

TEST(golden_gptp_signaling) {
    auto s = runSession("testdata/gptp_signaling.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK(countTransitions(*s, "-> GPTP_CAPABLE") == 1);
    CHECK(countTransitions(*s, "-> CAPABLE_TIMED_OUT") == 1);
    std::string st = s->stateJson();
    CHECK(st.find("\"requested_intervals\"") != std::string::npos);
    CHECK(st.find("\"time_sync\":\"-3 (125 ms)\"") != std::string::npos);
}

TEST(golden_milan_binding) {
    auto s = runSession("testdata/milan_binding.pcap");
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    // Full Milan §5.5.3 lifecycle as observed on the wire.
    CHECK(countTransitions(*s, "-> PRB_W_DELAY") == 2); // bind + rediscovery
    CHECK(countTransitions(*s, "-> PRB_W_RESP ") >= 2);
    CHECK(countTransitions(*s, "-> SETTLED_NO_RSV") == 2);
    CHECK(countTransitions(*s, "-> SETTLED_RSV_OK") == 2);
    CHECK(countTransitions(*s, "-> PRB_W_AVAIL") == 1);  // talker departed
    CHECK(countTransitions(*s, "-> UNBOUND") == 1);
    std::string st = s->stateJson();
    CHECK(st.find("\"probing_status\":\"PROBING_DISABLED\"") != std::string::npos);
    CHECK(st.find("\"milan_talkers\"") != std::string::npos);
    CHECK(st.find("\"probes_received\":2") != std::string::npos);
}

TEST(golden_malformed_never_crashes) {
    auto s = runSession("testdata/malformed.pcap");
    CHECK_EQ(s->status.load(), (int)Session::Done);
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)7);
    // The valid trailing packet still decodes (PA-5).
    bool sawValid = false;
    for (auto& e : s->events)
        if (e.kind == Kind::Packet && e.type == "ENTITY_AVAILABLE") sawValid = true;
    CHECK(sawValid);
}

TEST(golden_milan_scenario) {
    auto s = runSession("testdata/milan_scenario.pcap");
    CHECK_EQ(s->status.load(), (int)Session::Done);
    CHECK_EQ(s->decodeErrors.load(), (uint64_t)0);
    CHECK_EQ(s->packets.load(), (uint64_t)36);

    std::string st = s->stateJson();
    // PA-6: entities named from AEM enumeration.
    CHECK(st.find("\"name\":\"Stage Box FOH\"") != std::string::npos);
    CHECK(st.find("\"name\":\"Monitor Desk\"") != std::string::npos);
    // Full lifecycle ends disconnected/withdrawn/departing.
    CHECK(st.find("\"state\":\"DISCONNECTED\"") != std::string::npos);
    CHECK(st.find("\"state\":\"WITHDRAWN\"") != std::string::npos);
    CHECK(st.find("\"state\":\"DEPARTING\"") != std::string::npos);
    CHECK(st.find("\"state\":\"ACQUIRED\"") != std::string::npos);
    // The connection went through CONNECTED on the way.
    CHECK(countTransitions(*s, "-> CONNECTED") == 1);
    // Events are strictly ordered (CO-3).
    double last = -1;
    for (auto& e : s->events) {
        CHECK(e.ts >= last);
        last = e.ts;
    }
}
